# Generated by Django 5.2.17 on 2026-10-07 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0004_backfill_assignment_milestones'),
        ('incidents', '0008_retire_demo_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_report', 'New report'), ('report_received', 'Report received'), ('report_verified', 'Report verified'), ('report_rejected', 'Report rejected'), ('incident_created', 'Incident created'), ('incident_status_changed', 'Incident changed'), ('incident_resolved', 'Incident resolved'), ('new_assignment', 'New assignment'), ('assignment_cancelled', 'Assignment cancelled'), ('assignment_accepted', 'Assignment accepted'), ('assignment_rejected', 'Assignment rejected'), ('team_arrived', 'Team arrived'), ('assignment_completed', 'Assignment completed'), ('assistance_requested', 'Assistance requested')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=240)),
                ('event_key', models.CharField(max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.assignment')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incident')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.incidentreport')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_inbox_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='notification_recipient_event'), models.CheckConstraint(condition=models.Q(('type__in', ['new_report', 'report_received', 'report_verified', 'report_rejected', 'incident_created', 'incident_status_changed', 'incident_resolved', 'new_assignment', 'assignment_cancelled', 'assignment_accepted', 'assignment_rejected', 'team_arrived', 'assignment_completed', 'assistance_requested'])), name='notification_valid_type')],
            },
        ),
    ]
