# Generated by Django 5.2.17 on 2026-09-14 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_assignments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='incidents.incident')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='teams.responseteam')),
            ],
            options={
                'indexes': [models.Index(fields=['incident', 'status'], name='dispatch_as_inciden_460d1b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'en_route', 'on_scene'])), fields=('team',), name='one_active_assignment_per_team'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'completed', 'rejected', 'cancelled'])), name='assignment_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status__in', ['pending', 'accepted', 'en_route', 'on_scene'])), models.Q(('ended_at__isnull', False), ('status__in', ['completed', 'rejected', 'cancelled'])), _connector='OR'), name='assignment_end_matches_status'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('created_at')), _connector='OR'), name='assignment_end_after_creation')],
            },
        ),
    ]
