# Generated by Django 5.2.17 on 2026-09-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement', to='dispatch.assignment'),
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('assign', 'Assign'), ('transition', 'Transition'), ('cancel', 'Cancel'), ('reassign', 'Reassign')], max_length=15)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='dispatch.assignment')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('operation__in', ['assign', 'transition', 'cancel', 'reassign'])), name='assignment_history_operation'), models.CheckConstraint(condition=models.Q(('from_status', ''), ('from_status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'completed', 'rejected', 'cancelled']), _connector='OR'), name='assignment_history_from_status'), models.CheckConstraint(condition=models.Q(('to_status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'completed', 'rejected', 'cancelled'])), name='assignment_history_to_status'), models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='assignment_history_changed')],
            },
        ),
    ]
