# Generated by Django 5.2.17 on 2026-10-04 10:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatch_workflow'),
        ('incidents', '0005_incidentreport_allow_contact_and_more'),
        ('teams', '0003_latest_gps_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('problem', 'Problem'), ('support', 'Support')], max_length=15)),
                ('problem', models.CharField(blank=True, max_length=30)),
                ('support_type', models.CharField(blank=True, max_length=15)),
                ('note', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField()),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='one_active_assignment_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignment_valid_status',
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='assignment_end_matches_status',
        ),
        migrations.RemoveConstraint(
            model_name='assignmenthistory',
            name='assignment_history_from_status',
        ),
        migrations.RemoveConstraint(
            model_name='assignmenthistory',
            name='assignment_history_to_status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='dispatched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='en_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='responding_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('responding', 'Responding'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('responding', 'Responding'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmenthistory',
            name='to_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('on_scene', 'On scene'), ('responding', 'Responding'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'responding'])), fields=('team',), name='one_active_assignment_per_team'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'responding', 'completed', 'rejected', 'cancelled'])), name='assignment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'responding'])), models.Q(('ended_at__isnull', False), ('status__in', ['completed', 'rejected', 'cancelled'])), _connector='OR'), name='assignment_end_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='assignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', ''), ('from_status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'responding', 'completed', 'rejected', 'cancelled']), _connector='OR'), name='assignment_history_from_status'),
        ),
        migrations.AddConstraint(
            model_name='assignmenthistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['pending', 'accepted', 'en_route', 'on_scene', 'responding', 'completed', 'rejected', 'cancelled'])), name='assignment_history_to_status'),
        ),
        migrations.AddField(
            model_name='assignmentsignal',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsignal',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='dispatch.assignment'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsignal',
            constraint=models.UniqueConstraint(fields=('assignment', 'request_id'), name='unique_assignment_signal_request'),
        ),
    ]
