# Generated by Django 5.2.17 on 2026-09-14 15:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_enable_postgis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'incident categories',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='incidents.incidentcategory')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='incidents.incident')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_status_changes', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='incidents.incident')),
            ],
            options={
                'ordering': ['changed_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'created_at'], name='incidents_i_status_5d0930_idx'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'verified', 'dispatched', 'in_progress', 'resolved', 'cancelled'])), name='incident_valid_status'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['review_status', 'created_at'], name='incidents_i_review__a45e35_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidentreport',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'accepted', 'rejected'])), name='report_valid_review_status'),
        ),
        migrations.AddConstraint(
            model_name='incidentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', ''), ('from_status__in', ['new', 'verified', 'dispatched', 'in_progress', 'resolved', 'cancelled']), _connector='OR'), name='history_valid_from_status'),
        ),
        migrations.AddConstraint(
            model_name='incidentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['new', 'verified', 'dispatched', 'in_progress', 'resolved', 'cancelled'])), name='history_valid_to_status'),
        ),
        migrations.AddConstraint(
            model_name='incidentstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='history_status_changed'),
        ),
    ]
