# Generated by Django 5.2.17 on 2026-09-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='media_metadata',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incident_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
