# Generated by Django 5.2.17 on 2026-09-14 15:48

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_report_media_and_review_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReportLinkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Create incident from report'), ('link', 'Link report'), ('merge', 'Merge reports into incident')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category', 'created_at'], name='incident_cluster_time_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(models.F('category'), models.F('review_status'), django.db.models.functions.comparison.Coalesce('occurred_at', 'created_at'), name='report_cluster_time_idx'),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='candidate_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissed_by_reports', to='incidents.incidentreport'),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='dismissed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_dismissals', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='duplicatedismissal',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_dismissals', to='incidents.incidentreport'),
        ),
        migrations.AddField(
            model_name='incidentreportlinkhistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreportlinkhistory',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_link_history', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentreportlinkhistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_history', to='incidents.incidentreport'),
        ),
        migrations.AddConstraint(
            model_name='duplicatedismissal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate_report__isnull', False), ('incident__isnull', True)), models.Q(('candidate_report__isnull', True), ('incident__isnull', False)), _connector='OR'), name='dismissal_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='duplicatedismissal',
            constraint=models.CheckConstraint(condition=models.Q(('candidate_report__isnull', True), ('report__lt', models.F('candidate_report')), _connector='OR'), name='dismissal_report_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='duplicatedismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_report__isnull', False)), fields=('report', 'candidate_report'), name='unique_dismissed_report_pair'),
        ),
        migrations.AddConstraint(
            model_name='duplicatedismissal',
            constraint=models.UniqueConstraint(condition=models.Q(('incident__isnull', False)), fields=('report', 'incident'), name='unique_dismissed_incident'),
        ),
        migrations.AddConstraint(
            model_name='incidentreportlinkhistory',
            constraint=models.CheckConstraint(condition=models.Q(('operation__in', ['create', 'link', 'merge'])), name='report_link_valid_operation'),
        ),
    ]
