# Generated by Django 5.2.17 on 2026-10-04 15:23

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentreport_allow_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidentreport',
            name='report_cluster_time_idx',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='draft_request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(models.F('category'), models.F('review_status'), django.db.models.functions.comparison.Coalesce('occurred_at', 'submitted_at', 'created_at'), name='report_cluster_time_idx'),
        ),
    ]
