# Generated by Django 5.2.17 on 2026-09-28 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0004_duplicate_dismissals_and_link_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=44)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('version_id', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Awaiting upload'), ('ready', 'Confirmed'), ('deleting', 'Awaiting S3 cleanup'), ('deleted', 'Deleted'), ('failed', 'Cleanup failed')], default='pending', max_length=12)),
                ('upload_expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_attempts', models.PositiveSmallIntegerField(default=0)),
                ('cleanup_error', models.CharField(blank=True, max_length=40)),
                ('next_cleanup_at', models.DateTimeField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_media', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='incidents.incident')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='incidents.incidentreport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'next_cleanup_at'], name='media_cleanup_due')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('incident__isnull', True), ('report__isnull', False)), models.Q(('incident__isnull', False), ('report__isnull', True)), _connector='OR'), name='media_exactly_one_parent'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='media_positive_size'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'ready', 'deleting', 'deleted', 'failed'])), name='media_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='media_ready_confirmed')],
            },
        ),
    ]
