# Generated by Django 5.2.17 on 2026-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_media_upload_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='capture_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='capture_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='capture_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='capture_source',
            field=models.CharField(choices=[('upload', 'Upload'), ('camera', 'Client camera flow')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
