# Generated by Django 5.2.17 on 2026-10-07 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_mediaasset_capture_accuracy_and_more'),
        ('incidents', '0008_retire_demo_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='next_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='optimized_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='optimized_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='optimized_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='optimized_version_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_error',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_status',
            field=models.CharField(choices=[('not_required', 'Original only'), ('pending', 'Awaiting optimization'), ('processing', 'Optimizing'), ('ready', 'Optimized'), ('failed', 'Optimization failed')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['processing_status', 'next_processing_at'], name='media_processing_due'),
        ),
    ]
