# Generated by Django 5.2.17 on 2026-09-14 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='response_teams', to='incidents.incidentcategory')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['available', 'busy', 'offline'])), name='team_valid_status')],
            },
        ),
    ]
