# Generated by Django 5.2.17 on 2026-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_duplicate_dismissals_and_link_history'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='responseteam',
            index=models.Index(fields=['status'], name='team_readiness_idx'),
        ),
    ]
