# Generated by Django 5.2.17 on 2026-09-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_duplicate_dismissals_and_link_history'),
        ('teams', '0002_dispatch_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseteam',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseteam',
            name='location_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='responseteam',
            constraint=models.CheckConstraint(condition=models.Q(('location_accuracy__isnull', True), models.Q(('location_accuracy__gte', 0), ('location_accuracy__lte', 10000)), _connector='OR'), name='team_location_accuracy_range'),
        ),
    ]
